# Generated by Django 5.0.6 on 2024-12-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=255, verbose_name='Nome do Item')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('numero_contato', models.CharField(max_length=20, verbose_name='Número para Contato')),
                ('foto_item', models.ImageField(blank=True, null=True, upload_to='fotos_itens', verbose_name='Foto do Item')),
                ('nome_alimento', models.CharField(max_length=255, verbose_name='Nome do Alimento')),
            ],
        ),
    ]
