# Generated by Django 5.0.6 on 2024-12-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=255, verbose_name='Nome da Instituição')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
            ],
        ),
    ]
