# Generated by Django 5.0.6 on 2024-12-12 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_instituicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='nome_alimento',
        ),
        migrations.AddField(
            model_name='compra',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.instituicao', verbose_name='Instituição'),
            preserve_default=False,
        ),
    ]
